language: c
dist: trusty
sudo: required

notifications:
  email: false
git:
  submodules: true
  depth: 3

matrix:
  include:

  - os: linux
    compiler: gcc
    env:
      - PLATFORM='linux32'
      - PACKAGE='dummies-linux-32'
  - os: linux
    compiler: gcc
    env:
      - PLATFORM='linux64'
      - PACKAGE='dummies-linux-64'
  - os: osx
    compiler: clang
    env:
      - PLATFORM='macos'
      - PACKAGE='dummies-macos-universal'

install: bash ./pd.build/ci.install.sh
script: bash ./pd.build/ci.script.sh
after_success: bash ./pd.build/ci.test.sh ./tests/dummies-test.pd
before_deploy: bash ./pd.build/ci.package.sh LICENSE README.md src/ dummies/
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OvuuxKFL/kVKsQU7xVJ09PHAAgmlPqCh+GLib/nCfUQKVZ87De0UGoC95mHUHs7C+xkRVEIcL7uZZYhF5bMlIGdqPUjD1aPs2rLKr6aI9U7em7OH/+8eGLKUmIrST3d4/20iaAbSsaOwI5TElYv3w/rDoaIDznXLE0qhXUODajNG6KiXJybq7aUVXw9jfeSeMChBEQkP170qzEaNqJQ6Fu4CVT6jy1F5Bu806AJajvPwNnRTh44P6X/ESxyaohzTPQAPVMov/Qk9FFqf4yslC8up6bqLB//AzMJPgmEhYpOuuy5j0F7+duav5Lh0BWvB/8PDte4EhGzkci9RCZ4wpKHoUZd0BEHkwl39lSuMOCgTVj94zUnNu3Zos5nDxgyuY54RB+qq4bx0yQHpqISFReQqqAV7ZC5Cs65CFUjzSGYMRsKItq3Oqsk9EQO39pziMLFZsnhc/IDEK+cgnOmm1diqQWDknemLCUrcnQRul+7IchQuay1I0Zu26Z1jJ4u0Zf1tOa1vOIPP1iMgOghVrWyRWcanBUjfJTqsykkh+oWyvECnTwmcCUPW/e5hQwAflCC8EKIqy2BSmpEYJm7AfoV9k3qZs36xz9LyTsNcOCxVL+vZWRwyPAMkyVkpJ9Je3tFsMDf2EeyxrQTRTctZlvppzd0ISobObnJ88vPJX/4=
  file: $PACKAGE.zip
  on:
    tags: true
